#!/usr/bin/env bash
echo "===== GCZ Commands ====="
echo "gcz         → Master menu (restart, status, backup)"
echo "gczs        → Show current system + PM2 status"
echo "gczdiag     → Run system auto-heal & diagnose"
echo "gczapi      → Restart backend API"
echo "gczbot      → Restart Telegram bot"
echo "gczred      → Restart redirect engine"
echo "gczwd       → Restart watchdog"
echo "gczbackup   → Manual backup CSV + DB"
echo "sql         → Open Postgres shell"
echo "gitpushvps  → Push VPS to GitHub"
echo "gitpullvps  → Pull from GitHub to VPS"
echo "reload      → Reload .bashrc"
