// /var/www/html/gcz/ecosystem.config.cjs
module.exports = {
  apps: [
    {
      name: "gcz-api",
      script: "server.js",
      cwd: "/var/www/html/gcz",
      watch: false,
      instances: 1,
      exec_mode: "fork",
      max_memory_restart: "500M",
      env: {
        NODE_ENV: "production",
      },
      error_file: "./logs/gcz-api-error.log",
      out_file: "./logs/gcz-api-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
    },
    {
      name: "gcz-redirect",
      script: "python3",
      args: "backend/redirect.py",
      cwd: "/var/www/html/gcz",
      instances: 1,
      exec_mode: "fork",
      max_memory_restart: "200M",
      error_file: "./logs/gcz-redirect-error.log",
      out_file: "./logs/gcz-redirect-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
    },
    {
      name: "gcz-watchdog",
      script: "watchdog.js",
      cwd: "/var/www/html/gcz",
      instances: 1,
      exec_mode: "fork",
      max_memory_restart: "100M",
      error_file: "./logs/gcz-watchdog-error.log",
      out_file: "./logs/gcz-watchdog-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
    },
    {
      name: "gcz-bot",
      script: "start-bot.js",
      cwd: "/var/www/html/gcz",
      watch: false,
      instances: 1,
      exec_mode: "fork",
      max_memory_restart: "300M",
      env_file: ".env",
      env: {
        NODE_ENV: "production",
      },
      error_file: "./logs/gcz-bot-error.log",
      out_file: "./logs/gcz-bot-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
    },
    {
      name: "gcz-discord",
      script: "start-discord.js",
      cwd: "/var/www/html/gcz",
      watch: false,
      instances: 1,
      exec_mode: "fork",
      max_memory_restart: "300M",
      env_file: ".env",
      env: {
        NODE_ENV: "production",
      },
      error_file: "./logs/gcz-discord-error.log",
      out_file: "./logs/gcz-discord-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
    },
  ],
};
